openapi: '3.0.0'
info:
  version: 1.0.0
  title: Star Medical Wellness
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /patients:
    get:
      summary: List all patients
      operationId: listPatients
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: An paged array of patients
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patients'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create patient
      operationId: createPatient
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /patients/{patientId}:
    get:
      summary: Get patient info
      operationId: showPatientById
      parameters:
        - name: patientId
          in: path
          required: true
          description: The id of the patient to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patients'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /appointments:
    get:
      summary: List appointments
      operationId: listAppointments
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: An paged array of appointments
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointments'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Patient:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        condition:
          type: string
    Patients:
      type: array
      items:
        $ref: '#/components/schemas/Patient'
    Appointment:
      required:
        - id
        - date
      properties:
        id:
          type: integer
          format: int64
        date:
          type: string
        patientId:
          type: integer
          format: int64
    Appointments:
      type: array
      items:
        $ref: '#/components/schemas/Appointment'
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string